Migrate KS App Base to Python3, Jira:- FP-5100
fulfilio/kitchensink pull request #5
Opened 2019-01-21 13:26 UTC by amitasthana

2019-01-21 13:33 UTC, sayatul commented on manage.py
> +        print("Making shimpent %s wait" % shipment['id'])
change this to format

2019-01-21 13:36 UTC, sayatul commented
update runtime file, docker file and, scripts folder also

2019-01-21 13:37 UTC, sayatul requested changes

2019-01-21 13:37 UTC, sayatul commented on manage.py
> +        print("Making shimpent %s wait" % shipment['id'])
change this to format

2019-01-22 12:14 UTC, sayatul requested changes

2019-01-22 12:14 UTC, sayatul commented on kitchensink/dropshipping.py
> +    for shipment in list(shipments.values()):
remove list

2019-01-22 12:14 UTC, sayatul commented on kitchensink/dropshipping.py
> +        for row in list(quantum_data.values()):
same

2019-01-22 12:14 UTC, sayatul commented on kitchensink/dropshipping.py
> +    for shipment in list(shipments.values()):
same

2019-01-22 12:14 UTC, sayatul commented on kitchensink/utils.py
> +        |client_url(product.id) }}">{{ product.name }}</a>
indent

2019-01-22 12:14 UTC, sayatul commented on kitchensink/utils.py
> +        |client_url(domain=[('salable', '=', True)]) }}">
indent

2019-01-23 06:06 UTC, sayatul commented
LGTM

2019-01-24 09:43 UTC, tarunbhardwaj requested changes

2019-01-24 09:43 UTC, tarunbhardwaj commented on kitchensink/dropshipping.py
> +                (shipment['delivery_state'][-2:]
not readable at all.

Flake8 should not override readability of code.

2019-01-24 09:43 UTC, tarunbhardwaj commented on kitchensink/product.py
> +        [
why indent?

2019-01-24 09:43 UTC, tarunbhardwaj commented on kitchensink/utils.py
> +        <a href="{{ 'product.product'
not readable

2019-01-24 09:43 UTC, tarunbhardwaj commented on manage.py
> +                    'https://dto508s2j2p46.cloudfront.net/assets/'
http://example.com/path/to/thumb.png

2019-01-24 09:43 UTC, tarunbhardwaj commented on manage.py
>              'text': 'Tried to assign Mejuri Shipments',
`Tried to assign Shipments`

2019-01-25 11:23 UTC, tarunbhardwaj requested changes

2019-01-25 11:23 UTC, tarunbhardwaj commented on kitchensink/utils.py
> +        <a href="{{ 'product.product'
Really man, I have to comment on this specifically don't you think it is quite obvious to apply same change everywhere?

2019-01-25 11:23 UTC, tarunbhardwaj commented on manage.py
> +                'thumb_url': (
Ok, so why you need `(` now?

2019-01-25 11:57 UTC, tarunbhardwaj approved these changes

2019-01-25 11:57 UTC, merged